server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /api/v1/users/${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
