server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

test:
  message: Hello User Service from Config Server
